blank_issues_enabled: false
contact_links:
  - name: Start a Discussion
    about: "Start a discussion to share your experience with creedengo-javascript"
    url: https://github.com/green-code-initiative/creedengo-javascript/discussions/new/choose
